#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estimate
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Estimate")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 拡張メソッドの定義
    partial void OnCreated();
    partial void InsertM_Account(M_Account instance);
    partial void UpdateM_Account(M_Account instance);
    partial void DeleteM_Account(M_Account instance);
    partial void InsertM仕入先(M仕入先 instance);
    partial void UpdateM仕入先(M仕入先 instance);
    partial void DeleteM仕入先(M仕入先 instance);
    partial void InsertM商品(M商品 instance);
    partial void UpdateM商品(M商品 instance);
    partial void DeleteM商品(M商品 instance);
    partial void InsertM得意先(M得意先 instance);
    partial void UpdateM得意先(M得意先 instance);
    partial void DeleteM得意先(M得意先 instance);
    partial void InsertM発注先(M発注先 instance);
    partial void UpdateM発注先(M発注先 instance);
    partial void DeleteM発注先(M発注先 instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EstimateConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<M_Account> M_Account
		{
			get
			{
				return this.GetTable<M_Account>();
			}
		}
		
		public System.Data.Linq.Table<M仕入先> M仕入先
		{
			get
			{
				return this.GetTable<M仕入先>();
			}
		}
		
		public System.Data.Linq.Table<M商品> M商品
		{
			get
			{
				return this.GetTable<M商品>();
			}
		}
		
		public System.Data.Linq.Table<M得意先> M得意先
		{
			get
			{
				return this.GetTable<M得意先>();
			}
		}
		
		public System.Data.Linq.Table<M発注先> M発注先
		{
			get
			{
				return this.GetTable<M発注先>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_Account")]
	public partial class M_Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _Passwd;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnPasswdChanging(string value);
    partial void OnPasswdChanged();
    #endregion
		
		public M_Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passwd", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string Passwd
		{
			get
			{
				return this._Passwd;
			}
			set
			{
				if ((this._Passwd != value))
				{
					this.OnPasswdChanging(value);
					this.SendPropertyChanging();
					this._Passwd = value;
					this.SendPropertyChanged("Passwd");
					this.OnPasswdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M仕入先")]
	public partial class M仕入先 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _仕入先親CD;
		
		private string _仕入先子CD;
		
		private string _仕入先名1;
		
		private string _仕入先名2;
		
		private string _仕入先略称;
		
		private string _カタカナ名;
		
		private string _郵便番号;
		
		private string _住所1;
		
		private string _住所2;
		
		private string _電話番号;
		
		private string _FAX番号;
		
		private string _備考;
		
		private string _入力担当者CD;
		
		private string _作業場所名;
		
		private string _プログラムID;
		
		private string _登録端末名;
		
		private string _登録日時;
		
		private string _更新端末名;
		
		private string _更新日時;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On仕入先親CDChanging(string value);
    partial void On仕入先親CDChanged();
    partial void On仕入先子CDChanging(string value);
    partial void On仕入先子CDChanged();
    partial void On仕入先名1Changing(string value);
    partial void On仕入先名1Changed();
    partial void On仕入先名2Changing(string value);
    partial void On仕入先名2Changed();
    partial void On仕入先略称Changing(string value);
    partial void On仕入先略称Changed();
    partial void Onカタカナ名Changing(string value);
    partial void Onカタカナ名Changed();
    partial void On郵便番号Changing(string value);
    partial void On郵便番号Changed();
    partial void On住所1Changing(string value);
    partial void On住所1Changed();
    partial void On住所2Changing(string value);
    partial void On住所2Changed();
    partial void On電話番号Changing(string value);
    partial void On電話番号Changed();
    partial void OnFAX番号Changing(string value);
    partial void OnFAX番号Changed();
    partial void On備考Changing(string value);
    partial void On備考Changed();
    partial void On入力担当者CDChanging(string value);
    partial void On入力担当者CDChanged();
    partial void On作業場所名Changing(string value);
    partial void On作業場所名Changed();
    partial void OnプログラムIDChanging(string value);
    partial void OnプログラムIDChanged();
    partial void On登録端末名Changing(string value);
    partial void On登録端末名Changed();
    partial void On登録日時Changing(string value);
    partial void On登録日時Changed();
    partial void On更新端末名Changing(string value);
    partial void On更新端末名Changed();
    partial void On更新日時Changing(string value);
    partial void On更新日時Changed();
    #endregion
		
		public M仕入先()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_仕入先親CD", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string 仕入先親CD
		{
			get
			{
				return this._仕入先親CD;
			}
			set
			{
				if ((this._仕入先親CD != value))
				{
					this.On仕入先親CDChanging(value);
					this.SendPropertyChanging();
					this._仕入先親CD = value;
					this.SendPropertyChanged("仕入先親CD");
					this.On仕入先親CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_仕入先子CD", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string 仕入先子CD
		{
			get
			{
				return this._仕入先子CD;
			}
			set
			{
				if ((this._仕入先子CD != value))
				{
					this.On仕入先子CDChanging(value);
					this.SendPropertyChanging();
					this._仕入先子CD = value;
					this.SendPropertyChanged("仕入先子CD");
					this.On仕入先子CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_仕入先名1", DbType="VarChar(40)")]
		public string 仕入先名1
		{
			get
			{
				return this._仕入先名1;
			}
			set
			{
				if ((this._仕入先名1 != value))
				{
					this.On仕入先名1Changing(value);
					this.SendPropertyChanging();
					this._仕入先名1 = value;
					this.SendPropertyChanged("仕入先名1");
					this.On仕入先名1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_仕入先名2", DbType="VarChar(40)")]
		public string 仕入先名2
		{
			get
			{
				return this._仕入先名2;
			}
			set
			{
				if ((this._仕入先名2 != value))
				{
					this.On仕入先名2Changing(value);
					this.SendPropertyChanging();
					this._仕入先名2 = value;
					this.SendPropertyChanged("仕入先名2");
					this.On仕入先名2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_仕入先略称", DbType="VarChar(40)")]
		public string 仕入先略称
		{
			get
			{
				return this._仕入先略称;
			}
			set
			{
				if ((this._仕入先略称 != value))
				{
					this.On仕入先略称Changing(value);
					this.SendPropertyChanging();
					this._仕入先略称 = value;
					this.SendPropertyChanged("仕入先略称");
					this.On仕入先略称Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_カタカナ名", DbType="VarChar(40)")]
		public string カタカナ名
		{
			get
			{
				return this._カタカナ名;
			}
			set
			{
				if ((this._カタカナ名 != value))
				{
					this.Onカタカナ名Changing(value);
					this.SendPropertyChanging();
					this._カタカナ名 = value;
					this.SendPropertyChanged("カタカナ名");
					this.Onカタカナ名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_郵便番号", DbType="VarChar(8)")]
		public string 郵便番号
		{
			get
			{
				return this._郵便番号;
			}
			set
			{
				if ((this._郵便番号 != value))
				{
					this.On郵便番号Changing(value);
					this.SendPropertyChanging();
					this._郵便番号 = value;
					this.SendPropertyChanged("郵便番号");
					this.On郵便番号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_住所1", DbType="VarChar(40)")]
		public string 住所1
		{
			get
			{
				return this._住所1;
			}
			set
			{
				if ((this._住所1 != value))
				{
					this.On住所1Changing(value);
					this.SendPropertyChanging();
					this._住所1 = value;
					this.SendPropertyChanged("住所1");
					this.On住所1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_住所2", DbType="VarChar(40)")]
		public string 住所2
		{
			get
			{
				return this._住所2;
			}
			set
			{
				if ((this._住所2 != value))
				{
					this.On住所2Changing(value);
					this.SendPropertyChanging();
					this._住所2 = value;
					this.SendPropertyChanged("住所2");
					this.On住所2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_電話番号", DbType="VarChar(30)")]
		public string 電話番号
		{
			get
			{
				return this._電話番号;
			}
			set
			{
				if ((this._電話番号 != value))
				{
					this.On電話番号Changing(value);
					this.SendPropertyChanging();
					this._電話番号 = value;
					this.SendPropertyChanged("電話番号");
					this.On電話番号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX番号", DbType="VarChar(30)")]
		public string FAX番号
		{
			get
			{
				return this._FAX番号;
			}
			set
			{
				if ((this._FAX番号 != value))
				{
					this.OnFAX番号Changing(value);
					this.SendPropertyChanging();
					this._FAX番号 = value;
					this.SendPropertyChanged("FAX番号");
					this.OnFAX番号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_備考", DbType="VarChar(512)")]
		public string 備考
		{
			get
			{
				return this._備考;
			}
			set
			{
				if ((this._備考 != value))
				{
					this.On備考Changing(value);
					this.SendPropertyChanging();
					this._備考 = value;
					this.SendPropertyChanged("備考");
					this.On備考Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_入力担当者CD", DbType="VarChar(3)")]
		public string 入力担当者CD
		{
			get
			{
				return this._入力担当者CD;
			}
			set
			{
				if ((this._入力担当者CD != value))
				{
					this.On入力担当者CDChanging(value);
					this.SendPropertyChanging();
					this._入力担当者CD = value;
					this.SendPropertyChanged("入力担当者CD");
					this.On入力担当者CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_作業場所名", DbType="VarChar(10)")]
		public string 作業場所名
		{
			get
			{
				return this._作業場所名;
			}
			set
			{
				if ((this._作業場所名 != value))
				{
					this.On作業場所名Changing(value);
					this.SendPropertyChanging();
					this._作業場所名 = value;
					this.SendPropertyChanged("作業場所名");
					this.On作業場所名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_プログラムID", DbType="VarChar(60)")]
		public string プログラムID
		{
			get
			{
				return this._プログラムID;
			}
			set
			{
				if ((this._プログラムID != value))
				{
					this.OnプログラムIDChanging(value);
					this.SendPropertyChanging();
					this._プログラムID = value;
					this.SendPropertyChanged("プログラムID");
					this.OnプログラムIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登録端末名", DbType="VarChar(48)")]
		public string 登録端末名
		{
			get
			{
				return this._登録端末名;
			}
			set
			{
				if ((this._登録端末名 != value))
				{
					this.On登録端末名Changing(value);
					this.SendPropertyChanging();
					this._登録端末名 = value;
					this.SendPropertyChanged("登録端末名");
					this.On登録端末名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登録日時", DbType="VarChar(19)")]
		public string 登録日時
		{
			get
			{
				return this._登録日時;
			}
			set
			{
				if ((this._登録日時 != value))
				{
					this.On登録日時Changing(value);
					this.SendPropertyChanging();
					this._登録日時 = value;
					this.SendPropertyChanged("登録日時");
					this.On登録日時Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_更新端末名", DbType="VarChar(48)")]
		public string 更新端末名
		{
			get
			{
				return this._更新端末名;
			}
			set
			{
				if ((this._更新端末名 != value))
				{
					this.On更新端末名Changing(value);
					this.SendPropertyChanging();
					this._更新端末名 = value;
					this.SendPropertyChanged("更新端末名");
					this.On更新端末名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_更新日時", DbType="VarChar(19)")]
		public string 更新日時
		{
			get
			{
				return this._更新日時;
			}
			set
			{
				if ((this._更新日時 != value))
				{
					this.On更新日時Changing(value);
					this.SendPropertyChanging();
					this._更新日時 = value;
					this.SendPropertyChanged("更新日時");
					this.On更新日時Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M商品")]
	public partial class M商品 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _JANCD;
		
		private string _商品名;
		
		private string _カタカナ名;
		
		private string _メーカーCD;
		
		private string _仕入先CD;
		
		private string _発注先CD;
		
		private System.Nullable<char> _最大区分;
		
		private string _最大規格;
		
		private string _最大単位;
		
		private System.Nullable<decimal> _最大係数;
		
		private System.Nullable<decimal> _最大入数;
		
		private System.Nullable<char> _中間区分;
		
		private string _中間規格;
		
		private string _中間単位;
		
		private System.Nullable<decimal> _中間係数;
		
		private System.Nullable<decimal> _中間入数;
		
		private System.Nullable<char> _最小区分;
		
		private string _最小規格;
		
		private string _最小単位;
		
		private System.Nullable<decimal> _最小係数;
		
		private System.Nullable<decimal> _最小入数;
		
		private System.Nullable<decimal> _賞味期間;
		
		private System.Nullable<decimal> _仕入単価;
		
		private string _単価変更日付;
		
		private System.Nullable<decimal> _変更前単価;
		
		private string _販売期限日付;
		
		private string _備考;
		
		private string _入力担当者CD;
		
		private string _作業場所名;
		
		private string _プログラムID;
		
		private string _登録端末名;
		
		private string _登録日時;
		
		private string _更新端末名;
		
		private string _更新日時;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJANCDChanging(string value);
    partial void OnJANCDChanged();
    partial void On商品名Changing(string value);
    partial void On商品名Changed();
    partial void Onカタカナ名Changing(string value);
    partial void Onカタカナ名Changed();
    partial void OnメーカーCDChanging(string value);
    partial void OnメーカーCDChanged();
    partial void On仕入先CDChanging(string value);
    partial void On仕入先CDChanged();
    partial void On発注先CDChanging(string value);
    partial void On発注先CDChanged();
    partial void On最大区分Changing(System.Nullable<char> value);
    partial void On最大区分Changed();
    partial void On最大規格Changing(string value);
    partial void On最大規格Changed();
    partial void On最大単位Changing(string value);
    partial void On最大単位Changed();
    partial void On最大係数Changing(System.Nullable<decimal> value);
    partial void On最大係数Changed();
    partial void On最大入数Changing(System.Nullable<decimal> value);
    partial void On最大入数Changed();
    partial void On中間区分Changing(System.Nullable<char> value);
    partial void On中間区分Changed();
    partial void On中間規格Changing(string value);
    partial void On中間規格Changed();
    partial void On中間単位Changing(string value);
    partial void On中間単位Changed();
    partial void On中間係数Changing(System.Nullable<decimal> value);
    partial void On中間係数Changed();
    partial void On中間入数Changing(System.Nullable<decimal> value);
    partial void On中間入数Changed();
    partial void On最小区分Changing(System.Nullable<char> value);
    partial void On最小区分Changed();
    partial void On最小規格Changing(string value);
    partial void On最小規格Changed();
    partial void On最小単位Changing(string value);
    partial void On最小単位Changed();
    partial void On最小係数Changing(System.Nullable<decimal> value);
    partial void On最小係数Changed();
    partial void On最小入数Changing(System.Nullable<decimal> value);
    partial void On最小入数Changed();
    partial void On賞味期間Changing(System.Nullable<decimal> value);
    partial void On賞味期間Changed();
    partial void On仕入単価Changing(System.Nullable<decimal> value);
    partial void On仕入単価Changed();
    partial void On単価変更日付Changing(string value);
    partial void On単価変更日付Changed();
    partial void On変更前単価Changing(System.Nullable<decimal> value);
    partial void On変更前単価Changed();
    partial void On販売期限日付Changing(string value);
    partial void On販売期限日付Changed();
    partial void On備考Changing(string value);
    partial void On備考Changed();
    partial void On入力担当者CDChanging(string value);
    partial void On入力担当者CDChanged();
    partial void On作業場所名Changing(string value);
    partial void On作業場所名Changed();
    partial void OnプログラムIDChanging(string value);
    partial void OnプログラムIDChanged();
    partial void On登録端末名Changing(string value);
    partial void On登録端末名Changed();
    partial void On登録日時Changing(string value);
    partial void On登録日時Changed();
    partial void On更新端末名Changing(string value);
    partial void On更新端末名Changed();
    partial void On更新日時Changing(string value);
    partial void On更新日時Changed();
    #endregion
		
		public M商品()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JANCD", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string JANCD
		{
			get
			{
				return this._JANCD;
			}
			set
			{
				if ((this._JANCD != value))
				{
					this.OnJANCDChanging(value);
					this.SendPropertyChanging();
					this._JANCD = value;
					this.SendPropertyChanged("JANCD");
					this.OnJANCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_商品名", DbType="VarChar(40)")]
		public string 商品名
		{
			get
			{
				return this._商品名;
			}
			set
			{
				if ((this._商品名 != value))
				{
					this.On商品名Changing(value);
					this.SendPropertyChanging();
					this._商品名 = value;
					this.SendPropertyChanged("商品名");
					this.On商品名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_カタカナ名", DbType="VarChar(40)")]
		public string カタカナ名
		{
			get
			{
				return this._カタカナ名;
			}
			set
			{
				if ((this._カタカナ名 != value))
				{
					this.Onカタカナ名Changing(value);
					this.SendPropertyChanging();
					this._カタカナ名 = value;
					this.SendPropertyChanged("カタカナ名");
					this.Onカタカナ名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_メーカーCD", DbType="Char(5)")]
		public string メーカーCD
		{
			get
			{
				return this._メーカーCD;
			}
			set
			{
				if ((this._メーカーCD != value))
				{
					this.OnメーカーCDChanging(value);
					this.SendPropertyChanging();
					this._メーカーCD = value;
					this.SendPropertyChanged("メーカーCD");
					this.OnメーカーCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_仕入先CD", DbType="Char(8)")]
		public string 仕入先CD
		{
			get
			{
				return this._仕入先CD;
			}
			set
			{
				if ((this._仕入先CD != value))
				{
					this.On仕入先CDChanging(value);
					this.SendPropertyChanging();
					this._仕入先CD = value;
					this.SendPropertyChanged("仕入先CD");
					this.On仕入先CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_発注先CD", DbType="Char(8)")]
		public string 発注先CD
		{
			get
			{
				return this._発注先CD;
			}
			set
			{
				if ((this._発注先CD != value))
				{
					this.On発注先CDChanging(value);
					this.SendPropertyChanging();
					this._発注先CD = value;
					this.SendPropertyChanged("発注先CD");
					this.On発注先CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_最大区分", DbType="Char(1)")]
		public System.Nullable<char> 最大区分
		{
			get
			{
				return this._最大区分;
			}
			set
			{
				if ((this._最大区分 != value))
				{
					this.On最大区分Changing(value);
					this.SendPropertyChanging();
					this._最大区分 = value;
					this.SendPropertyChanged("最大区分");
					this.On最大区分Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_最大規格", DbType="VarChar(20)")]
		public string 最大規格
		{
			get
			{
				return this._最大規格;
			}
			set
			{
				if ((this._最大規格 != value))
				{
					this.On最大規格Changing(value);
					this.SendPropertyChanging();
					this._最大規格 = value;
					this.SendPropertyChanged("最大規格");
					this.On最大規格Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_最大単位", DbType="VarChar(10)")]
		public string 最大単位
		{
			get
			{
				return this._最大単位;
			}
			set
			{
				if ((this._最大単位 != value))
				{
					this.On最大単位Changing(value);
					this.SendPropertyChanging();
					this._最大単位 = value;
					this.SendPropertyChanged("最大単位");
					this.On最大単位Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_最大係数", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> 最大係数
		{
			get
			{
				return this._最大係数;
			}
			set
			{
				if ((this._最大係数 != value))
				{
					this.On最大係数Changing(value);
					this.SendPropertyChanging();
					this._最大係数 = value;
					this.SendPropertyChanged("最大係数");
					this.On最大係数Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_最大入数", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> 最大入数
		{
			get
			{
				return this._最大入数;
			}
			set
			{
				if ((this._最大入数 != value))
				{
					this.On最大入数Changing(value);
					this.SendPropertyChanging();
					this._最大入数 = value;
					this.SendPropertyChanged("最大入数");
					this.On最大入数Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_中間区分", DbType="Char(1)")]
		public System.Nullable<char> 中間区分
		{
			get
			{
				return this._中間区分;
			}
			set
			{
				if ((this._中間区分 != value))
				{
					this.On中間区分Changing(value);
					this.SendPropertyChanging();
					this._中間区分 = value;
					this.SendPropertyChanged("中間区分");
					this.On中間区分Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_中間規格", DbType="VarChar(20)")]
		public string 中間規格
		{
			get
			{
				return this._中間規格;
			}
			set
			{
				if ((this._中間規格 != value))
				{
					this.On中間規格Changing(value);
					this.SendPropertyChanging();
					this._中間規格 = value;
					this.SendPropertyChanged("中間規格");
					this.On中間規格Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_中間単位", DbType="VarChar(10)")]
		public string 中間単位
		{
			get
			{
				return this._中間単位;
			}
			set
			{
				if ((this._中間単位 != value))
				{
					this.On中間単位Changing(value);
					this.SendPropertyChanging();
					this._中間単位 = value;
					this.SendPropertyChanged("中間単位");
					this.On中間単位Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_中間係数", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> 中間係数
		{
			get
			{
				return this._中間係数;
			}
			set
			{
				if ((this._中間係数 != value))
				{
					this.On中間係数Changing(value);
					this.SendPropertyChanging();
					this._中間係数 = value;
					this.SendPropertyChanged("中間係数");
					this.On中間係数Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_中間入数", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> 中間入数
		{
			get
			{
				return this._中間入数;
			}
			set
			{
				if ((this._中間入数 != value))
				{
					this.On中間入数Changing(value);
					this.SendPropertyChanging();
					this._中間入数 = value;
					this.SendPropertyChanged("中間入数");
					this.On中間入数Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_最小区分", DbType="Char(1)")]
		public System.Nullable<char> 最小区分
		{
			get
			{
				return this._最小区分;
			}
			set
			{
				if ((this._最小区分 != value))
				{
					this.On最小区分Changing(value);
					this.SendPropertyChanging();
					this._最小区分 = value;
					this.SendPropertyChanged("最小区分");
					this.On最小区分Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_最小規格", DbType="VarChar(20)")]
		public string 最小規格
		{
			get
			{
				return this._最小規格;
			}
			set
			{
				if ((this._最小規格 != value))
				{
					this.On最小規格Changing(value);
					this.SendPropertyChanging();
					this._最小規格 = value;
					this.SendPropertyChanged("最小規格");
					this.On最小規格Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_最小単位", DbType="VarChar(10)")]
		public string 最小単位
		{
			get
			{
				return this._最小単位;
			}
			set
			{
				if ((this._最小単位 != value))
				{
					this.On最小単位Changing(value);
					this.SendPropertyChanging();
					this._最小単位 = value;
					this.SendPropertyChanged("最小単位");
					this.On最小単位Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_最小係数", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> 最小係数
		{
			get
			{
				return this._最小係数;
			}
			set
			{
				if ((this._最小係数 != value))
				{
					this.On最小係数Changing(value);
					this.SendPropertyChanging();
					this._最小係数 = value;
					this.SendPropertyChanged("最小係数");
					this.On最小係数Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_最小入数", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> 最小入数
		{
			get
			{
				return this._最小入数;
			}
			set
			{
				if ((this._最小入数 != value))
				{
					this.On最小入数Changing(value);
					this.SendPropertyChanging();
					this._最小入数 = value;
					this.SendPropertyChanged("最小入数");
					this.On最小入数Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_賞味期間", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> 賞味期間
		{
			get
			{
				return this._賞味期間;
			}
			set
			{
				if ((this._賞味期間 != value))
				{
					this.On賞味期間Changing(value);
					this.SendPropertyChanging();
					this._賞味期間 = value;
					this.SendPropertyChanged("賞味期間");
					this.On賞味期間Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_仕入単価", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> 仕入単価
		{
			get
			{
				return this._仕入単価;
			}
			set
			{
				if ((this._仕入単価 != value))
				{
					this.On仕入単価Changing(value);
					this.SendPropertyChanging();
					this._仕入単価 = value;
					this.SendPropertyChanged("仕入単価");
					this.On仕入単価Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_単価変更日付", DbType="Char(10)")]
		public string 単価変更日付
		{
			get
			{
				return this._単価変更日付;
			}
			set
			{
				if ((this._単価変更日付 != value))
				{
					this.On単価変更日付Changing(value);
					this.SendPropertyChanging();
					this._単価変更日付 = value;
					this.SendPropertyChanged("単価変更日付");
					this.On単価変更日付Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_変更前単価", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> 変更前単価
		{
			get
			{
				return this._変更前単価;
			}
			set
			{
				if ((this._変更前単価 != value))
				{
					this.On変更前単価Changing(value);
					this.SendPropertyChanging();
					this._変更前単価 = value;
					this.SendPropertyChanged("変更前単価");
					this.On変更前単価Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_販売期限日付", DbType="Char(10)")]
		public string 販売期限日付
		{
			get
			{
				return this._販売期限日付;
			}
			set
			{
				if ((this._販売期限日付 != value))
				{
					this.On販売期限日付Changing(value);
					this.SendPropertyChanging();
					this._販売期限日付 = value;
					this.SendPropertyChanged("販売期限日付");
					this.On販売期限日付Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_備考", DbType="VarChar(512)")]
		public string 備考
		{
			get
			{
				return this._備考;
			}
			set
			{
				if ((this._備考 != value))
				{
					this.On備考Changing(value);
					this.SendPropertyChanging();
					this._備考 = value;
					this.SendPropertyChanged("備考");
					this.On備考Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_入力担当者CD", DbType="VarChar(3)")]
		public string 入力担当者CD
		{
			get
			{
				return this._入力担当者CD;
			}
			set
			{
				if ((this._入力担当者CD != value))
				{
					this.On入力担当者CDChanging(value);
					this.SendPropertyChanging();
					this._入力担当者CD = value;
					this.SendPropertyChanged("入力担当者CD");
					this.On入力担当者CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_作業場所名", DbType="VarChar(10)")]
		public string 作業場所名
		{
			get
			{
				return this._作業場所名;
			}
			set
			{
				if ((this._作業場所名 != value))
				{
					this.On作業場所名Changing(value);
					this.SendPropertyChanging();
					this._作業場所名 = value;
					this.SendPropertyChanged("作業場所名");
					this.On作業場所名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_プログラムID", DbType="VarChar(60)")]
		public string プログラムID
		{
			get
			{
				return this._プログラムID;
			}
			set
			{
				if ((this._プログラムID != value))
				{
					this.OnプログラムIDChanging(value);
					this.SendPropertyChanging();
					this._プログラムID = value;
					this.SendPropertyChanged("プログラムID");
					this.OnプログラムIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登録端末名", DbType="VarChar(48)")]
		public string 登録端末名
		{
			get
			{
				return this._登録端末名;
			}
			set
			{
				if ((this._登録端末名 != value))
				{
					this.On登録端末名Changing(value);
					this.SendPropertyChanging();
					this._登録端末名 = value;
					this.SendPropertyChanged("登録端末名");
					this.On登録端末名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登録日時", DbType="VarChar(19)")]
		public string 登録日時
		{
			get
			{
				return this._登録日時;
			}
			set
			{
				if ((this._登録日時 != value))
				{
					this.On登録日時Changing(value);
					this.SendPropertyChanging();
					this._登録日時 = value;
					this.SendPropertyChanged("登録日時");
					this.On登録日時Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_更新端末名", DbType="VarChar(48)")]
		public string 更新端末名
		{
			get
			{
				return this._更新端末名;
			}
			set
			{
				if ((this._更新端末名 != value))
				{
					this.On更新端末名Changing(value);
					this.SendPropertyChanging();
					this._更新端末名 = value;
					this.SendPropertyChanged("更新端末名");
					this.On更新端末名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_更新日時", DbType="VarChar(19)")]
		public string 更新日時
		{
			get
			{
				return this._更新日時;
			}
			set
			{
				if ((this._更新日時 != value))
				{
					this.On更新日時Changing(value);
					this.SendPropertyChanging();
					this._更新日時 = value;
					this.SendPropertyChanged("更新日時");
					this.On更新日時Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M得意先")]
	public partial class M得意先 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _得意先親CD;
		
		private string _得意先子CD;
		
		private string _得意先名1;
		
		private string _得意先名2;
		
		private string _得意先略称;
		
		private string _カタカナ名;
		
		private string _郵便番号;
		
		private string _住所1;
		
		private string _住所2;
		
		private string _電話番号;
		
		private string _FAX番号;
		
		private string _請求先CD;
		
		private string _請求先名1;
		
		private string _請求先名2;
		
		private string _請求先郵便番号;
		
		private string _請求先住所1;
		
		private string _請求先住所2;
		
		private string _請求先電話番号;
		
		private string _請求先FAX番号;
		
		private string _請求締日1;
		
		private string _集金区分1;
		
		private string _集金日1;
		
		private string _請求締日2;
		
		private string _集金区分2;
		
		private string _集金日2;
		
		private System.Nullable<char> _請求書区分;
		
		private string _請求書種別;
		
		private System.Nullable<char> _消費税区分1;
		
		private System.Nullable<char> _消費税区分2;
		
		private System.Nullable<char> _消費税区分3;
		
		private System.Nullable<char> _不良債権区分;
		
		private string _営業担当者CD;
		
		private string _開設担当者CD;
		
		private string _配送ライン;
		
		private string _ランク;
		
		private string _工場区分;
		
		private System.Nullable<char> _ピッキング区分;
		
		private string _配達区分;
		
		private string _運送便区分;
		
		private string _納品日数符号;
		
		private string _納品日数;
		
		private string _取引開始日付;
		
		private string _最新売上日付;
		
		private string _前回請求日付;
		
		private string _今回請求日付;
		
		private string _総額開始日付;
		
		private System.Nullable<decimal> _西村便手数料;
		
		private System.Nullable<char> _回収区分;
		
		private string _備考;
		
		private string _入力担当者CD;
		
		private string _作業場所名;
		
		private string _プログラムID;
		
		private string _登録端末名;
		
		private string _登録日時;
		
		private string _更新端末名;
		
		private string _更新日時;
		
		private string _請求更新端末名;
		
		private string _請求更新日時;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On得意先親CDChanging(string value);
    partial void On得意先親CDChanged();
    partial void On得意先子CDChanging(string value);
    partial void On得意先子CDChanged();
    partial void On得意先名1Changing(string value);
    partial void On得意先名1Changed();
    partial void On得意先名2Changing(string value);
    partial void On得意先名2Changed();
    partial void On得意先略称Changing(string value);
    partial void On得意先略称Changed();
    partial void Onカタカナ名Changing(string value);
    partial void Onカタカナ名Changed();
    partial void On郵便番号Changing(string value);
    partial void On郵便番号Changed();
    partial void On住所1Changing(string value);
    partial void On住所1Changed();
    partial void On住所2Changing(string value);
    partial void On住所2Changed();
    partial void On電話番号Changing(string value);
    partial void On電話番号Changed();
    partial void OnFAX番号Changing(string value);
    partial void OnFAX番号Changed();
    partial void On請求先CDChanging(string value);
    partial void On請求先CDChanged();
    partial void On請求先名1Changing(string value);
    partial void On請求先名1Changed();
    partial void On請求先名2Changing(string value);
    partial void On請求先名2Changed();
    partial void On請求先郵便番号Changing(string value);
    partial void On請求先郵便番号Changed();
    partial void On請求先住所1Changing(string value);
    partial void On請求先住所1Changed();
    partial void On請求先住所2Changing(string value);
    partial void On請求先住所2Changed();
    partial void On請求先電話番号Changing(string value);
    partial void On請求先電話番号Changed();
    partial void On請求先FAX番号Changing(string value);
    partial void On請求先FAX番号Changed();
    partial void On請求締日1Changing(string value);
    partial void On請求締日1Changed();
    partial void On集金区分1Changing(string value);
    partial void On集金区分1Changed();
    partial void On集金日1Changing(string value);
    partial void On集金日1Changed();
    partial void On請求締日2Changing(string value);
    partial void On請求締日2Changed();
    partial void On集金区分2Changing(string value);
    partial void On集金区分2Changed();
    partial void On集金日2Changing(string value);
    partial void On集金日2Changed();
    partial void On請求書区分Changing(System.Nullable<char> value);
    partial void On請求書区分Changed();
    partial void On請求書種別Changing(string value);
    partial void On請求書種別Changed();
    partial void On消費税区分1Changing(System.Nullable<char> value);
    partial void On消費税区分1Changed();
    partial void On消費税区分2Changing(System.Nullable<char> value);
    partial void On消費税区分2Changed();
    partial void On消費税区分3Changing(System.Nullable<char> value);
    partial void On消費税区分3Changed();
    partial void On不良債権区分Changing(System.Nullable<char> value);
    partial void On不良債権区分Changed();
    partial void On営業担当者CDChanging(string value);
    partial void On営業担当者CDChanged();
    partial void On開設担当者CDChanging(string value);
    partial void On開設担当者CDChanged();
    partial void On配送ラインChanging(string value);
    partial void On配送ラインChanged();
    partial void OnランクChanging(string value);
    partial void OnランクChanged();
    partial void On工場区分Changing(string value);
    partial void On工場区分Changed();
    partial void Onピッキング区分Changing(System.Nullable<char> value);
    partial void Onピッキング区分Changed();
    partial void On配達区分Changing(string value);
    partial void On配達区分Changed();
    partial void On運送便区分Changing(string value);
    partial void On運送便区分Changed();
    partial void On納品日数符号Changing(string value);
    partial void On納品日数符号Changed();
    partial void On納品日数Changing(string value);
    partial void On納品日数Changed();
    partial void On取引開始日付Changing(string value);
    partial void On取引開始日付Changed();
    partial void On最新売上日付Changing(string value);
    partial void On最新売上日付Changed();
    partial void On前回請求日付Changing(string value);
    partial void On前回請求日付Changed();
    partial void On今回請求日付Changing(string value);
    partial void On今回請求日付Changed();
    partial void On総額開始日付Changing(string value);
    partial void On総額開始日付Changed();
    partial void On西村便手数料Changing(System.Nullable<decimal> value);
    partial void On西村便手数料Changed();
    partial void On回収区分Changing(System.Nullable<char> value);
    partial void On回収区分Changed();
    partial void On備考Changing(string value);
    partial void On備考Changed();
    partial void On入力担当者CDChanging(string value);
    partial void On入力担当者CDChanged();
    partial void On作業場所名Changing(string value);
    partial void On作業場所名Changed();
    partial void OnプログラムIDChanging(string value);
    partial void OnプログラムIDChanged();
    partial void On登録端末名Changing(string value);
    partial void On登録端末名Changed();
    partial void On登録日時Changing(string value);
    partial void On登録日時Changed();
    partial void On更新端末名Changing(string value);
    partial void On更新端末名Changed();
    partial void On更新日時Changing(string value);
    partial void On更新日時Changed();
    partial void On請求更新端末名Changing(string value);
    partial void On請求更新端末名Changed();
    partial void On請求更新日時Changing(string value);
    partial void On請求更新日時Changed();
    #endregion
		
		public M得意先()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_得意先親CD", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string 得意先親CD
		{
			get
			{
				return this._得意先親CD;
			}
			set
			{
				if ((this._得意先親CD != value))
				{
					this.On得意先親CDChanging(value);
					this.SendPropertyChanging();
					this._得意先親CD = value;
					this.SendPropertyChanged("得意先親CD");
					this.On得意先親CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_得意先子CD", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string 得意先子CD
		{
			get
			{
				return this._得意先子CD;
			}
			set
			{
				if ((this._得意先子CD != value))
				{
					this.On得意先子CDChanging(value);
					this.SendPropertyChanging();
					this._得意先子CD = value;
					this.SendPropertyChanged("得意先子CD");
					this.On得意先子CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_得意先名1", DbType="VarChar(40)")]
		public string 得意先名1
		{
			get
			{
				return this._得意先名1;
			}
			set
			{
				if ((this._得意先名1 != value))
				{
					this.On得意先名1Changing(value);
					this.SendPropertyChanging();
					this._得意先名1 = value;
					this.SendPropertyChanged("得意先名1");
					this.On得意先名1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_得意先名2", DbType="VarChar(40)")]
		public string 得意先名2
		{
			get
			{
				return this._得意先名2;
			}
			set
			{
				if ((this._得意先名2 != value))
				{
					this.On得意先名2Changing(value);
					this.SendPropertyChanging();
					this._得意先名2 = value;
					this.SendPropertyChanged("得意先名2");
					this.On得意先名2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_得意先略称", DbType="VarChar(40)")]
		public string 得意先略称
		{
			get
			{
				return this._得意先略称;
			}
			set
			{
				if ((this._得意先略称 != value))
				{
					this.On得意先略称Changing(value);
					this.SendPropertyChanging();
					this._得意先略称 = value;
					this.SendPropertyChanged("得意先略称");
					this.On得意先略称Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_カタカナ名", DbType="VarChar(40)")]
		public string カタカナ名
		{
			get
			{
				return this._カタカナ名;
			}
			set
			{
				if ((this._カタカナ名 != value))
				{
					this.Onカタカナ名Changing(value);
					this.SendPropertyChanging();
					this._カタカナ名 = value;
					this.SendPropertyChanged("カタカナ名");
					this.Onカタカナ名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_郵便番号", DbType="VarChar(8)")]
		public string 郵便番号
		{
			get
			{
				return this._郵便番号;
			}
			set
			{
				if ((this._郵便番号 != value))
				{
					this.On郵便番号Changing(value);
					this.SendPropertyChanging();
					this._郵便番号 = value;
					this.SendPropertyChanged("郵便番号");
					this.On郵便番号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_住所1", DbType="VarChar(40)")]
		public string 住所1
		{
			get
			{
				return this._住所1;
			}
			set
			{
				if ((this._住所1 != value))
				{
					this.On住所1Changing(value);
					this.SendPropertyChanging();
					this._住所1 = value;
					this.SendPropertyChanged("住所1");
					this.On住所1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_住所2", DbType="VarChar(40)")]
		public string 住所2
		{
			get
			{
				return this._住所2;
			}
			set
			{
				if ((this._住所2 != value))
				{
					this.On住所2Changing(value);
					this.SendPropertyChanging();
					this._住所2 = value;
					this.SendPropertyChanged("住所2");
					this.On住所2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_電話番号", DbType="VarChar(30)")]
		public string 電話番号
		{
			get
			{
				return this._電話番号;
			}
			set
			{
				if ((this._電話番号 != value))
				{
					this.On電話番号Changing(value);
					this.SendPropertyChanging();
					this._電話番号 = value;
					this.SendPropertyChanged("電話番号");
					this.On電話番号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX番号", DbType="VarChar(30)")]
		public string FAX番号
		{
			get
			{
				return this._FAX番号;
			}
			set
			{
				if ((this._FAX番号 != value))
				{
					this.OnFAX番号Changing(value);
					this.SendPropertyChanging();
					this._FAX番号 = value;
					this.SendPropertyChanged("FAX番号");
					this.OnFAX番号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_請求先CD", DbType="Char(8)")]
		public string 請求先CD
		{
			get
			{
				return this._請求先CD;
			}
			set
			{
				if ((this._請求先CD != value))
				{
					this.On請求先CDChanging(value);
					this.SendPropertyChanging();
					this._請求先CD = value;
					this.SendPropertyChanged("請求先CD");
					this.On請求先CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_請求先名1", DbType="VarChar(40)")]
		public string 請求先名1
		{
			get
			{
				return this._請求先名1;
			}
			set
			{
				if ((this._請求先名1 != value))
				{
					this.On請求先名1Changing(value);
					this.SendPropertyChanging();
					this._請求先名1 = value;
					this.SendPropertyChanged("請求先名1");
					this.On請求先名1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_請求先名2", DbType="VarChar(40)")]
		public string 請求先名2
		{
			get
			{
				return this._請求先名2;
			}
			set
			{
				if ((this._請求先名2 != value))
				{
					this.On請求先名2Changing(value);
					this.SendPropertyChanging();
					this._請求先名2 = value;
					this.SendPropertyChanged("請求先名2");
					this.On請求先名2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_請求先郵便番号", DbType="VarChar(8)")]
		public string 請求先郵便番号
		{
			get
			{
				return this._請求先郵便番号;
			}
			set
			{
				if ((this._請求先郵便番号 != value))
				{
					this.On請求先郵便番号Changing(value);
					this.SendPropertyChanging();
					this._請求先郵便番号 = value;
					this.SendPropertyChanged("請求先郵便番号");
					this.On請求先郵便番号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_請求先住所1", DbType="VarChar(40)")]
		public string 請求先住所1
		{
			get
			{
				return this._請求先住所1;
			}
			set
			{
				if ((this._請求先住所1 != value))
				{
					this.On請求先住所1Changing(value);
					this.SendPropertyChanging();
					this._請求先住所1 = value;
					this.SendPropertyChanged("請求先住所1");
					this.On請求先住所1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_請求先住所2", DbType="VarChar(40)")]
		public string 請求先住所2
		{
			get
			{
				return this._請求先住所2;
			}
			set
			{
				if ((this._請求先住所2 != value))
				{
					this.On請求先住所2Changing(value);
					this.SendPropertyChanging();
					this._請求先住所2 = value;
					this.SendPropertyChanged("請求先住所2");
					this.On請求先住所2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_請求先電話番号", DbType="VarChar(30)")]
		public string 請求先電話番号
		{
			get
			{
				return this._請求先電話番号;
			}
			set
			{
				if ((this._請求先電話番号 != value))
				{
					this.On請求先電話番号Changing(value);
					this.SendPropertyChanging();
					this._請求先電話番号 = value;
					this.SendPropertyChanged("請求先電話番号");
					this.On請求先電話番号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_請求先FAX番号", DbType="VarChar(30)")]
		public string 請求先FAX番号
		{
			get
			{
				return this._請求先FAX番号;
			}
			set
			{
				if ((this._請求先FAX番号 != value))
				{
					this.On請求先FAX番号Changing(value);
					this.SendPropertyChanging();
					this._請求先FAX番号 = value;
					this.SendPropertyChanged("請求先FAX番号");
					this.On請求先FAX番号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_請求締日1", DbType="Char(2)")]
		public string 請求締日1
		{
			get
			{
				return this._請求締日1;
			}
			set
			{
				if ((this._請求締日1 != value))
				{
					this.On請求締日1Changing(value);
					this.SendPropertyChanging();
					this._請求締日1 = value;
					this.SendPropertyChanged("請求締日1");
					this.On請求締日1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_集金区分1", DbType="VarChar(1)")]
		public string 集金区分1
		{
			get
			{
				return this._集金区分1;
			}
			set
			{
				if ((this._集金区分1 != value))
				{
					this.On集金区分1Changing(value);
					this.SendPropertyChanging();
					this._集金区分1 = value;
					this.SendPropertyChanged("集金区分1");
					this.On集金区分1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_集金日1", DbType="Char(2)")]
		public string 集金日1
		{
			get
			{
				return this._集金日1;
			}
			set
			{
				if ((this._集金日1 != value))
				{
					this.On集金日1Changing(value);
					this.SendPropertyChanging();
					this._集金日1 = value;
					this.SendPropertyChanged("集金日1");
					this.On集金日1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_請求締日2", DbType="Char(2)")]
		public string 請求締日2
		{
			get
			{
				return this._請求締日2;
			}
			set
			{
				if ((this._請求締日2 != value))
				{
					this.On請求締日2Changing(value);
					this.SendPropertyChanging();
					this._請求締日2 = value;
					this.SendPropertyChanged("請求締日2");
					this.On請求締日2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_集金区分2", DbType="VarChar(1)")]
		public string 集金区分2
		{
			get
			{
				return this._集金区分2;
			}
			set
			{
				if ((this._集金区分2 != value))
				{
					this.On集金区分2Changing(value);
					this.SendPropertyChanging();
					this._集金区分2 = value;
					this.SendPropertyChanged("集金区分2");
					this.On集金区分2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_集金日2", DbType="Char(2)")]
		public string 集金日2
		{
			get
			{
				return this._集金日2;
			}
			set
			{
				if ((this._集金日2 != value))
				{
					this.On集金日2Changing(value);
					this.SendPropertyChanging();
					this._集金日2 = value;
					this.SendPropertyChanged("集金日2");
					this.On集金日2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_請求書区分", DbType="Char(1)")]
		public System.Nullable<char> 請求書区分
		{
			get
			{
				return this._請求書区分;
			}
			set
			{
				if ((this._請求書区分 != value))
				{
					this.On請求書区分Changing(value);
					this.SendPropertyChanging();
					this._請求書区分 = value;
					this.SendPropertyChanged("請求書区分");
					this.On請求書区分Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_請求書種別", DbType="VarChar(1)")]
		public string 請求書種別
		{
			get
			{
				return this._請求書種別;
			}
			set
			{
				if ((this._請求書種別 != value))
				{
					this.On請求書種別Changing(value);
					this.SendPropertyChanging();
					this._請求書種別 = value;
					this.SendPropertyChanged("請求書種別");
					this.On請求書種別Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_消費税区分1", DbType="Char(1)")]
		public System.Nullable<char> 消費税区分1
		{
			get
			{
				return this._消費税区分1;
			}
			set
			{
				if ((this._消費税区分1 != value))
				{
					this.On消費税区分1Changing(value);
					this.SendPropertyChanging();
					this._消費税区分1 = value;
					this.SendPropertyChanged("消費税区分1");
					this.On消費税区分1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_消費税区分2", DbType="Char(1)")]
		public System.Nullable<char> 消費税区分2
		{
			get
			{
				return this._消費税区分2;
			}
			set
			{
				if ((this._消費税区分2 != value))
				{
					this.On消費税区分2Changing(value);
					this.SendPropertyChanging();
					this._消費税区分2 = value;
					this.SendPropertyChanged("消費税区分2");
					this.On消費税区分2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_消費税区分3", DbType="Char(1)")]
		public System.Nullable<char> 消費税区分3
		{
			get
			{
				return this._消費税区分3;
			}
			set
			{
				if ((this._消費税区分3 != value))
				{
					this.On消費税区分3Changing(value);
					this.SendPropertyChanging();
					this._消費税区分3 = value;
					this.SendPropertyChanged("消費税区分3");
					this.On消費税区分3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_不良債権区分", DbType="Char(1)")]
		public System.Nullable<char> 不良債権区分
		{
			get
			{
				return this._不良債権区分;
			}
			set
			{
				if ((this._不良債権区分 != value))
				{
					this.On不良債権区分Changing(value);
					this.SendPropertyChanging();
					this._不良債権区分 = value;
					this.SendPropertyChanged("不良債権区分");
					this.On不良債権区分Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_営業担当者CD", DbType="Char(3)")]
		public string 営業担当者CD
		{
			get
			{
				return this._営業担当者CD;
			}
			set
			{
				if ((this._営業担当者CD != value))
				{
					this.On営業担当者CDChanging(value);
					this.SendPropertyChanging();
					this._営業担当者CD = value;
					this.SendPropertyChanged("営業担当者CD");
					this.On営業担当者CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_開設担当者CD", DbType="Char(3)")]
		public string 開設担当者CD
		{
			get
			{
				return this._開設担当者CD;
			}
			set
			{
				if ((this._開設担当者CD != value))
				{
					this.On開設担当者CDChanging(value);
					this.SendPropertyChanging();
					this._開設担当者CD = value;
					this.SendPropertyChanged("開設担当者CD");
					this.On開設担当者CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_配送ライン", DbType="VarChar(2)")]
		public string 配送ライン
		{
			get
			{
				return this._配送ライン;
			}
			set
			{
				if ((this._配送ライン != value))
				{
					this.On配送ラインChanging(value);
					this.SendPropertyChanging();
					this._配送ライン = value;
					this.SendPropertyChanged("配送ライン");
					this.On配送ラインChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ランク", DbType="VarChar(1)")]
		public string ランク
		{
			get
			{
				return this._ランク;
			}
			set
			{
				if ((this._ランク != value))
				{
					this.OnランクChanging(value);
					this.SendPropertyChanging();
					this._ランク = value;
					this.SendPropertyChanged("ランク");
					this.OnランクChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_工場区分", DbType="VarChar(2)")]
		public string 工場区分
		{
			get
			{
				return this._工場区分;
			}
			set
			{
				if ((this._工場区分 != value))
				{
					this.On工場区分Changing(value);
					this.SendPropertyChanging();
					this._工場区分 = value;
					this.SendPropertyChanged("工場区分");
					this.On工場区分Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ピッキング区分", DbType="Char(1)")]
		public System.Nullable<char> ピッキング区分
		{
			get
			{
				return this._ピッキング区分;
			}
			set
			{
				if ((this._ピッキング区分 != value))
				{
					this.Onピッキング区分Changing(value);
					this.SendPropertyChanging();
					this._ピッキング区分 = value;
					this.SendPropertyChanged("ピッキング区分");
					this.Onピッキング区分Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_配達区分", DbType="Char(2)")]
		public string 配達区分
		{
			get
			{
				return this._配達区分;
			}
			set
			{
				if ((this._配達区分 != value))
				{
					this.On配達区分Changing(value);
					this.SendPropertyChanging();
					this._配達区分 = value;
					this.SendPropertyChanged("配達区分");
					this.On配達区分Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_運送便区分", DbType="Char(2)")]
		public string 運送便区分
		{
			get
			{
				return this._運送便区分;
			}
			set
			{
				if ((this._運送便区分 != value))
				{
					this.On運送便区分Changing(value);
					this.SendPropertyChanging();
					this._運送便区分 = value;
					this.SendPropertyChanged("運送便区分");
					this.On運送便区分Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_納品日数符号", DbType="VarChar(1)")]
		public string 納品日数符号
		{
			get
			{
				return this._納品日数符号;
			}
			set
			{
				if ((this._納品日数符号 != value))
				{
					this.On納品日数符号Changing(value);
					this.SendPropertyChanging();
					this._納品日数符号 = value;
					this.SendPropertyChanged("納品日数符号");
					this.On納品日数符号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_納品日数", DbType="Char(2)")]
		public string 納品日数
		{
			get
			{
				return this._納品日数;
			}
			set
			{
				if ((this._納品日数 != value))
				{
					this.On納品日数Changing(value);
					this.SendPropertyChanging();
					this._納品日数 = value;
					this.SendPropertyChanged("納品日数");
					this.On納品日数Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_取引開始日付", DbType="Char(10)")]
		public string 取引開始日付
		{
			get
			{
				return this._取引開始日付;
			}
			set
			{
				if ((this._取引開始日付 != value))
				{
					this.On取引開始日付Changing(value);
					this.SendPropertyChanging();
					this._取引開始日付 = value;
					this.SendPropertyChanged("取引開始日付");
					this.On取引開始日付Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_最新売上日付", DbType="Char(10)")]
		public string 最新売上日付
		{
			get
			{
				return this._最新売上日付;
			}
			set
			{
				if ((this._最新売上日付 != value))
				{
					this.On最新売上日付Changing(value);
					this.SendPropertyChanging();
					this._最新売上日付 = value;
					this.SendPropertyChanged("最新売上日付");
					this.On最新売上日付Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_前回請求日付", DbType="Char(10)")]
		public string 前回請求日付
		{
			get
			{
				return this._前回請求日付;
			}
			set
			{
				if ((this._前回請求日付 != value))
				{
					this.On前回請求日付Changing(value);
					this.SendPropertyChanging();
					this._前回請求日付 = value;
					this.SendPropertyChanged("前回請求日付");
					this.On前回請求日付Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_今回請求日付", DbType="Char(10)")]
		public string 今回請求日付
		{
			get
			{
				return this._今回請求日付;
			}
			set
			{
				if ((this._今回請求日付 != value))
				{
					this.On今回請求日付Changing(value);
					this.SendPropertyChanging();
					this._今回請求日付 = value;
					this.SendPropertyChanged("今回請求日付");
					this.On今回請求日付Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_総額開始日付", DbType="Char(10)")]
		public string 総額開始日付
		{
			get
			{
				return this._総額開始日付;
			}
			set
			{
				if ((this._総額開始日付 != value))
				{
					this.On総額開始日付Changing(value);
					this.SendPropertyChanging();
					this._総額開始日付 = value;
					this.SendPropertyChanged("総額開始日付");
					this.On総額開始日付Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_西村便手数料", DbType="Decimal(3,1)")]
		public System.Nullable<decimal> 西村便手数料
		{
			get
			{
				return this._西村便手数料;
			}
			set
			{
				if ((this._西村便手数料 != value))
				{
					this.On西村便手数料Changing(value);
					this.SendPropertyChanging();
					this._西村便手数料 = value;
					this.SendPropertyChanged("西村便手数料");
					this.On西村便手数料Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_回収区分", DbType="Char(1)")]
		public System.Nullable<char> 回収区分
		{
			get
			{
				return this._回収区分;
			}
			set
			{
				if ((this._回収区分 != value))
				{
					this.On回収区分Changing(value);
					this.SendPropertyChanging();
					this._回収区分 = value;
					this.SendPropertyChanged("回収区分");
					this.On回収区分Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_備考", DbType="VarChar(512)")]
		public string 備考
		{
			get
			{
				return this._備考;
			}
			set
			{
				if ((this._備考 != value))
				{
					this.On備考Changing(value);
					this.SendPropertyChanging();
					this._備考 = value;
					this.SendPropertyChanged("備考");
					this.On備考Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_入力担当者CD", DbType="VarChar(3)")]
		public string 入力担当者CD
		{
			get
			{
				return this._入力担当者CD;
			}
			set
			{
				if ((this._入力担当者CD != value))
				{
					this.On入力担当者CDChanging(value);
					this.SendPropertyChanging();
					this._入力担当者CD = value;
					this.SendPropertyChanged("入力担当者CD");
					this.On入力担当者CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_作業場所名", DbType="VarChar(10)")]
		public string 作業場所名
		{
			get
			{
				return this._作業場所名;
			}
			set
			{
				if ((this._作業場所名 != value))
				{
					this.On作業場所名Changing(value);
					this.SendPropertyChanging();
					this._作業場所名 = value;
					this.SendPropertyChanged("作業場所名");
					this.On作業場所名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_プログラムID", DbType="VarChar(60)")]
		public string プログラムID
		{
			get
			{
				return this._プログラムID;
			}
			set
			{
				if ((this._プログラムID != value))
				{
					this.OnプログラムIDChanging(value);
					this.SendPropertyChanging();
					this._プログラムID = value;
					this.SendPropertyChanged("プログラムID");
					this.OnプログラムIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登録端末名", DbType="VarChar(48)")]
		public string 登録端末名
		{
			get
			{
				return this._登録端末名;
			}
			set
			{
				if ((this._登録端末名 != value))
				{
					this.On登録端末名Changing(value);
					this.SendPropertyChanging();
					this._登録端末名 = value;
					this.SendPropertyChanged("登録端末名");
					this.On登録端末名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登録日時", DbType="VarChar(19)")]
		public string 登録日時
		{
			get
			{
				return this._登録日時;
			}
			set
			{
				if ((this._登録日時 != value))
				{
					this.On登録日時Changing(value);
					this.SendPropertyChanging();
					this._登録日時 = value;
					this.SendPropertyChanged("登録日時");
					this.On登録日時Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_更新端末名", DbType="VarChar(48)")]
		public string 更新端末名
		{
			get
			{
				return this._更新端末名;
			}
			set
			{
				if ((this._更新端末名 != value))
				{
					this.On更新端末名Changing(value);
					this.SendPropertyChanging();
					this._更新端末名 = value;
					this.SendPropertyChanged("更新端末名");
					this.On更新端末名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_更新日時", DbType="VarChar(19)")]
		public string 更新日時
		{
			get
			{
				return this._更新日時;
			}
			set
			{
				if ((this._更新日時 != value))
				{
					this.On更新日時Changing(value);
					this.SendPropertyChanging();
					this._更新日時 = value;
					this.SendPropertyChanged("更新日時");
					this.On更新日時Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_請求更新端末名", DbType="VarChar(48)")]
		public string 請求更新端末名
		{
			get
			{
				return this._請求更新端末名;
			}
			set
			{
				if ((this._請求更新端末名 != value))
				{
					this.On請求更新端末名Changing(value);
					this.SendPropertyChanging();
					this._請求更新端末名 = value;
					this.SendPropertyChanged("請求更新端末名");
					this.On請求更新端末名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_請求更新日時", DbType="VarChar(19)")]
		public string 請求更新日時
		{
			get
			{
				return this._請求更新日時;
			}
			set
			{
				if ((this._請求更新日時 != value))
				{
					this.On請求更新日時Changing(value);
					this.SendPropertyChanging();
					this._請求更新日時 = value;
					this.SendPropertyChanged("請求更新日時");
					this.On請求更新日時Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M発注先")]
	public partial class M発注先 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _発注先親CD;
		
		private string _発注先子CD;
		
		private string _発注先名1;
		
		private string _発注先名2;
		
		private string _発注先略称;
		
		private string _カタカナ名;
		
		private string _郵便番号;
		
		private string _住所1;
		
		private string _住所2;
		
		private string _電話番号;
		
		private string _FAX番号;
		
		private string _自動FAX番号;
		
		private string _備考;
		
		private string _入力担当者CD;
		
		private string _作業場所名;
		
		private string _プログラムID;
		
		private string _登録端末名;
		
		private string _登録日時;
		
		private string _更新端末名;
		
		private string _更新日時;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On発注先親CDChanging(string value);
    partial void On発注先親CDChanged();
    partial void On発注先子CDChanging(string value);
    partial void On発注先子CDChanged();
    partial void On発注先名1Changing(string value);
    partial void On発注先名1Changed();
    partial void On発注先名2Changing(string value);
    partial void On発注先名2Changed();
    partial void On発注先略称Changing(string value);
    partial void On発注先略称Changed();
    partial void Onカタカナ名Changing(string value);
    partial void Onカタカナ名Changed();
    partial void On郵便番号Changing(string value);
    partial void On郵便番号Changed();
    partial void On住所1Changing(string value);
    partial void On住所1Changed();
    partial void On住所2Changing(string value);
    partial void On住所2Changed();
    partial void On電話番号Changing(string value);
    partial void On電話番号Changed();
    partial void OnFAX番号Changing(string value);
    partial void OnFAX番号Changed();
    partial void On自動FAX番号Changing(string value);
    partial void On自動FAX番号Changed();
    partial void On備考Changing(string value);
    partial void On備考Changed();
    partial void On入力担当者CDChanging(string value);
    partial void On入力担当者CDChanged();
    partial void On作業場所名Changing(string value);
    partial void On作業場所名Changed();
    partial void OnプログラムIDChanging(string value);
    partial void OnプログラムIDChanged();
    partial void On登録端末名Changing(string value);
    partial void On登録端末名Changed();
    partial void On登録日時Changing(string value);
    partial void On登録日時Changed();
    partial void On更新端末名Changing(string value);
    partial void On更新端末名Changed();
    partial void On更新日時Changing(string value);
    partial void On更新日時Changed();
    #endregion
		
		public M発注先()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_発注先親CD", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string 発注先親CD
		{
			get
			{
				return this._発注先親CD;
			}
			set
			{
				if ((this._発注先親CD != value))
				{
					this.On発注先親CDChanging(value);
					this.SendPropertyChanging();
					this._発注先親CD = value;
					this.SendPropertyChanged("発注先親CD");
					this.On発注先親CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_発注先子CD", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string 発注先子CD
		{
			get
			{
				return this._発注先子CD;
			}
			set
			{
				if ((this._発注先子CD != value))
				{
					this.On発注先子CDChanging(value);
					this.SendPropertyChanging();
					this._発注先子CD = value;
					this.SendPropertyChanged("発注先子CD");
					this.On発注先子CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_発注先名1", DbType="VarChar(40)")]
		public string 発注先名1
		{
			get
			{
				return this._発注先名1;
			}
			set
			{
				if ((this._発注先名1 != value))
				{
					this.On発注先名1Changing(value);
					this.SendPropertyChanging();
					this._発注先名1 = value;
					this.SendPropertyChanged("発注先名1");
					this.On発注先名1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_発注先名2", DbType="VarChar(40)")]
		public string 発注先名2
		{
			get
			{
				return this._発注先名2;
			}
			set
			{
				if ((this._発注先名2 != value))
				{
					this.On発注先名2Changing(value);
					this.SendPropertyChanging();
					this._発注先名2 = value;
					this.SendPropertyChanged("発注先名2");
					this.On発注先名2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_発注先略称", DbType="VarChar(40)")]
		public string 発注先略称
		{
			get
			{
				return this._発注先略称;
			}
			set
			{
				if ((this._発注先略称 != value))
				{
					this.On発注先略称Changing(value);
					this.SendPropertyChanging();
					this._発注先略称 = value;
					this.SendPropertyChanged("発注先略称");
					this.On発注先略称Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_カタカナ名", DbType="VarChar(40)")]
		public string カタカナ名
		{
			get
			{
				return this._カタカナ名;
			}
			set
			{
				if ((this._カタカナ名 != value))
				{
					this.Onカタカナ名Changing(value);
					this.SendPropertyChanging();
					this._カタカナ名 = value;
					this.SendPropertyChanged("カタカナ名");
					this.Onカタカナ名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_郵便番号", DbType="VarChar(8)")]
		public string 郵便番号
		{
			get
			{
				return this._郵便番号;
			}
			set
			{
				if ((this._郵便番号 != value))
				{
					this.On郵便番号Changing(value);
					this.SendPropertyChanging();
					this._郵便番号 = value;
					this.SendPropertyChanged("郵便番号");
					this.On郵便番号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_住所1", DbType="VarChar(40)")]
		public string 住所1
		{
			get
			{
				return this._住所1;
			}
			set
			{
				if ((this._住所1 != value))
				{
					this.On住所1Changing(value);
					this.SendPropertyChanging();
					this._住所1 = value;
					this.SendPropertyChanged("住所1");
					this.On住所1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_住所2", DbType="VarChar(40)")]
		public string 住所2
		{
			get
			{
				return this._住所2;
			}
			set
			{
				if ((this._住所2 != value))
				{
					this.On住所2Changing(value);
					this.SendPropertyChanging();
					this._住所2 = value;
					this.SendPropertyChanged("住所2");
					this.On住所2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_電話番号", DbType="VarChar(30)")]
		public string 電話番号
		{
			get
			{
				return this._電話番号;
			}
			set
			{
				if ((this._電話番号 != value))
				{
					this.On電話番号Changing(value);
					this.SendPropertyChanging();
					this._電話番号 = value;
					this.SendPropertyChanged("電話番号");
					this.On電話番号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX番号", DbType="VarChar(30)")]
		public string FAX番号
		{
			get
			{
				return this._FAX番号;
			}
			set
			{
				if ((this._FAX番号 != value))
				{
					this.OnFAX番号Changing(value);
					this.SendPropertyChanging();
					this._FAX番号 = value;
					this.SendPropertyChanged("FAX番号");
					this.OnFAX番号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_自動FAX番号", DbType="VarChar(20)")]
		public string 自動FAX番号
		{
			get
			{
				return this._自動FAX番号;
			}
			set
			{
				if ((this._自動FAX番号 != value))
				{
					this.On自動FAX番号Changing(value);
					this.SendPropertyChanging();
					this._自動FAX番号 = value;
					this.SendPropertyChanged("自動FAX番号");
					this.On自動FAX番号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_備考", DbType="VarChar(512)")]
		public string 備考
		{
			get
			{
				return this._備考;
			}
			set
			{
				if ((this._備考 != value))
				{
					this.On備考Changing(value);
					this.SendPropertyChanging();
					this._備考 = value;
					this.SendPropertyChanged("備考");
					this.On備考Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_入力担当者CD", DbType="VarChar(3)")]
		public string 入力担当者CD
		{
			get
			{
				return this._入力担当者CD;
			}
			set
			{
				if ((this._入力担当者CD != value))
				{
					this.On入力担当者CDChanging(value);
					this.SendPropertyChanging();
					this._入力担当者CD = value;
					this.SendPropertyChanged("入力担当者CD");
					this.On入力担当者CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_作業場所名", DbType="VarChar(10)")]
		public string 作業場所名
		{
			get
			{
				return this._作業場所名;
			}
			set
			{
				if ((this._作業場所名 != value))
				{
					this.On作業場所名Changing(value);
					this.SendPropertyChanging();
					this._作業場所名 = value;
					this.SendPropertyChanged("作業場所名");
					this.On作業場所名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_プログラムID", DbType="VarChar(60)")]
		public string プログラムID
		{
			get
			{
				return this._プログラムID;
			}
			set
			{
				if ((this._プログラムID != value))
				{
					this.OnプログラムIDChanging(value);
					this.SendPropertyChanging();
					this._プログラムID = value;
					this.SendPropertyChanged("プログラムID");
					this.OnプログラムIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登録端末名", DbType="VarChar(48)")]
		public string 登録端末名
		{
			get
			{
				return this._登録端末名;
			}
			set
			{
				if ((this._登録端末名 != value))
				{
					this.On登録端末名Changing(value);
					this.SendPropertyChanging();
					this._登録端末名 = value;
					this.SendPropertyChanged("登録端末名");
					this.On登録端末名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_登録日時", DbType="VarChar(19)")]
		public string 登録日時
		{
			get
			{
				return this._登録日時;
			}
			set
			{
				if ((this._登録日時 != value))
				{
					this.On登録日時Changing(value);
					this.SendPropertyChanging();
					this._登録日時 = value;
					this.SendPropertyChanged("登録日時");
					this.On登録日時Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_更新端末名", DbType="VarChar(48)")]
		public string 更新端末名
		{
			get
			{
				return this._更新端末名;
			}
			set
			{
				if ((this._更新端末名 != value))
				{
					this.On更新端末名Changing(value);
					this.SendPropertyChanging();
					this._更新端末名 = value;
					this.SendPropertyChanged("更新端末名");
					this.On更新端末名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_更新日時", DbType="VarChar(19)")]
		public string 更新日時
		{
			get
			{
				return this._更新日時;
			}
			set
			{
				if ((this._更新日時 != value))
				{
					this.On更新日時Changing(value);
					this.SendPropertyChanging();
					this._更新日時 = value;
					this.SendPropertyChanged("更新日時");
					this.On更新日時Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
